development:
  domain: "http://api-test.eshopinion.com"
  opinions_end_point: "opinions"
  opinions_limit: 10

production:
  domain: "http://api-test.eshopinion.com"
  opinions_end_point: "opinions"
  opinions_limit: 10

